version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Adjust if your requirements.txt is in a subdirectory
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
